title: Jeffrey van de Kamp
description: Hoi ik ben Jeffrey. Mijn collega’s kennen me als een vriendelijke en communicatief vaardige functioneel beheerder.
show_downloads: true
logo: /assets/img/jvdk.jpeg
theme: jekyll-theme-minimal
